// src/utils/product-data.js
export const getProductData = () => {
  return Promise.resolve([
    {
      id: 1,
      name: 'Siro Lựu Đỏ Diệp Trà Premium',
      slug: 'siro-luu-do-diep-tra-premium',
      description: 'Siro lựu đỏ thơm ngon, vị chua ngọt cân bằng, thích hợp pha chế đồ uống cao cấp',
      price: 89000,
      originalPrice: 99000,
      image: '/images/products/siro-luu-do.jpg',
      category: 'syrup',
      inStock: true,
      sold: 156,
      isNew: true,
      isOnSale: true,
      createdAt: '2024-08-15'
    },
    {
      id: 2,
      name: 'Mứt Ổi Hồng Diệp Trà',
      slug: 'mut-oi-hong-diep-tra',
      description: 'Mứt ổi hồng ngọt ngào, hương vị tự nhiên, phù hợp với trà hoa quả',
      price: 75000,
      image: '/images/products/mut-oi-hong.jpg',
      category: 'jam',
      inStock: true,
      sold: 89,
      isNew: false,
      isOnSale: false,
      createdAt: '2024-08-10'
    },
    {
      id: 3,
      name: 'Bột Kem Trứng Diệp Trà',
      slug: 'bot-kem-trung-diep-tra',
      description: 'Bột kem trứng cao cấp, tạo vị béo ngậy cho trà sữa và các loại đồ uống khác',
      price: 125000,
      image: '/images/products/bot-kem-trung.jpg',
      category: 'powder',
      inStock: true,
      sold: 234,
      isNew: false,
      isOnSale: false,
      createdAt: '2024-08-05'
    },
    {
      id: 4,
      name: 'Siro Vải Diệp Trà',
      slug: 'siro-vai-diep-tra',
      description: 'Siro vải tươi mát, hương vị ngọt dịu, thích hợp cho mùa hè',
      price: 79000,
      originalPrice: 89000,
      image: '/images/products/siro-vai.jpg',
      category: 'syrup',
      inStock: false,
      sold: 67,
      isNew: false,
      isOnSale: true,
      createdAt: '2024-08-01'
    },
    {
      id: 5,
      name: 'Thạch Dừa Diệp Trà',
      slug: 'thach-dua-diep-tra',
      description: 'Thạch dừa tươi ngon, kết cấu dai giòn, bổ sung cho đồ uống thêm hấp dẫn',
      price: 45000,
      image: '/images/products/thach-dua.jpg',
      category: 'topping',
      inStock: true,
      sold: 178,
      isNew: true,
      isOnSale: false,
      createdAt: '2024-07-28'
    },
    {
      id: 6,
      name: 'Mứt Dương Chi Cam Lộ',
      slug: 'mut-duong-chi-cam-lo',
      description: 'Mứt dương chi cam lộ độc đáo, vị ngọt thanh, màu sắc bắt mắt',
      price: 95000,
      image: '/images/products/mut-duong-chi.jpg',
      category: 'jam',
      inStock: true,
      sold: 123,
      isNew: false,
      isOnSale: false,
      createdAt: '2024-07-25'
    },
    {
      id: 7,
      name: 'Siro Đào Diệp Trà Premium',
      slug: 'siro-dao-diep-tra-premium',
      description: 'Siro đào thơm ngọt, hương vị tự nhiên, thích hợp pha chế cocktail và mocktail',
      price: 92000,
      originalPrice: 105000,
      image: '/images/products/siro-dao.jpg',
      category: 'syrup',
      inStock: true,
      sold: 98,
      isNew: true,
      isOnSale: true,
      createdAt: '2024-07-20'
    },
    {
      id: 8,
      name: 'Bột Matcha Diệp Trà Organic',
      slug: 'bot-matcha-diep-tra-organic',
      description: 'Bột matcha organic cao cấp, vị đắng nhẹ, màu xanh tự nhiên',
      price: 150000,
      image: '/images/products/bot-matcha.jpg',
      category: 'powder',
      inStock: true,
      sold: 67,
      isNew: true,
      isOnSale: false,
      createdAt: '2024-07-15'
    },
    // Add more products to reach 59 total for pagination demo
    ...Array.from({ length: 51 }, (_, index) => ({
      id: 9 + index,
      name: `Sản phẩm ${9 + index}`,
      slug: `san-pham-${9 + index}`,
      description: `Mô tả sản phẩm ${9 + index} với chất lượng cao, phù hợp cho pha chế`,
      price: Math.floor(Math.random() * 200000) + 50000,
      image: `/images/products/product-${(index % 8) + 1}.jpg`,
      category: ['syrup', 'jam', 'powder', 'topping'][index % 4],
      inStock: Math.random() > 0.1,
      sold: Math.floor(Math.random() * 300),
      isNew: Math.random() > 0.8,
      isOnSale: Math.random() > 0.7,
      createdAt: new Date(2024, 6, Math.floor(Math.random() * 30) + 1).toISOString().split('T')[0]
    }))
  ]);
};
